spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_localizacao
    username: root
    password: qwe123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        show_sql: true
        format_sql: true

server:
  port: 8081